### ISSUE TITLE
Searching for Wii Games

### ISSUE THREAD

**Issue by DwarfLop** [y21/wiiset-bot#4]
Add a command to search for Wii games, you can type in an name or an keyword, or discover games with an category like "Arcarde". OwO

**Comment by DwarfLop** [comment]
*Posted by Terax on Discord*
you could use https://www.gametdb.com/Wii as title db

**Comment by y21** [comment]
That's a great idea, I'm thinking of implementing it into the bot. It wont be easy since that website does not have an API (from what I've seen, I could be wrong at this point, correct me if I am).
I also could display whether the requested game is supported by Wiimmfi (the Nintendo WFC replacement) or not, it might be interesting for some people.
Thank you.

**Comment by y21** [comment]
Added in https://github.com/y21/wiiset-bot/commit/b60b0f15fc948c78ffcaeb45b0ab57a5ad1b1407.
Instead of using gametdb.com, it uses Nintendo's official "API".
(https://www.nintendo.com/json/content/get/filter/game)
